### ISSUE TITLE
AttributeError: 'int' object has no attribute 'clone'

### ISSUE THREAD

**Issue by redhat12345** [IssamLaradji/M-ADDA#1]
I got the following error.

File "/media/redhat/DATA/M-ADDA/datasets/uspsBig.py", line 69, in __getitem__
    img, label = self.X[index].clone(), self.y[index].clone()
AttributeError: 'int' object has no attribute 'clone'

**Comment by IssamLaradji** [comment]
Are you using Pytorch 0.4? if you have Pytorch 0.4 or higher `self.y[index]` will be a tensor instead of an integer, which then allows you to apply the function `.clone()` to it

**Comment by redhat12345** [comment]
Thanks. But I am getting the following error. 

Traceback (most recent call last):
  File "main.py", line 28, in <module>
    print("CUDA: %s" % torch.version.cuda)
AttributeError: module 'torch.version' has no attribute 'cuda'

**Comment by IssamLaradji** [comment]
Awesome, did it work?

**Comment by redhat12345** [comment]
I got the following error after some epochs . 

File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/datasets'

**Comment by redhat12345** [comment]
Hi, May I know how you plot the graph for your paper? May I get the code for plotting graph, please?

**Comment by IssamLaradji** [comment]
Thanks for the interest! are you referring to the plot in Figure 9? I used `PrettyPlots` as uploaded here: https://github.com/IssamLaradji/PrettyPlots

**Comment by redhat12345** [comment]
Actually, I am talking about figure 3 and 8 in the paper.

**Comment by IssamLaradji** [comment]
I generated Figure 8 using the `visEmbed(exp_dict)` function in `addons/vis.py`.
I generated Figure 3 using `visdom` scatter plot `https://github.com/facebookresearch/visdom`

Cheers.

**Comment by redhat12345** [comment]
@IssamLaradji  May I know how you draw the Figure 8?

**Comment by IssamLaradji** [comment]
@redhat12345 are you using Python 3? if you are using Python 2 then you get this error you mentioned because it does not use `absolute` import (it uses relative import instead).

I generated Figure 8 using the `visEmbed(exp_dict) `function in `addons/vis.py`.

**Comment by redhat12345** [comment]
@IssamLaradji  I am using Python 3. When I run the command:
$ python3 addons/vis.py 

It gives me some warning this time and did not produce any images in the Summarises folder that i created here. 

"/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
"
